### ISSUE TITLE
Doesnt run when shipped on app

### ISSUE THREAD

**Issue by vsouto** [hughred22/YouTube-Video-Listing-Ionic-Mobile-App#2]
I did a clone of this project and worked pretty well on my local ionic web environment.

But when i deploy it to a device, it seems that it does not connect to the channel, and does not list the videos. 

Did anyone successfully tested it on a device?

**Comment by hughred22** [comment]
Hi Victor, 

Thanks for checking out this build. What device you are deploying on? iOs 9 with Xcode 7? If that is the case, it is Ionic need to monkey patch to work with iOs 9. You can find out more info here: http://blog.ionic.io/preparing-for-ios-9/

**Comment by vsouto** [comment]
Hey hugh, thanks for the reply!

I tested on my Nexus (android 5).

One guess of mine is that i had referenced an external javascript.
Im gonna try again tomorrow.

**Comment by hughred22** [comment]
Hi Vsouto, 

How was your tests? Just FYI, if you referenced external javascript library, you have to make sure you use the full path like so: https://www.youtube.com/iframe_api
Not: //www.youtube.com/iframe_api

This is common issue b/c :// will load file:// instead of https://

Also, please use https instead of http b/c iOs9 require secure connection.
